### ISSUE TITLE
Use Discord API data to differentiate between created and joined threads

### ISSUE THREAD

**Issue by Burrito5152** [nextcord/nextcord#967] opened 2023-01-07 18:35 UTC
### Summary

Created and joined threads are not the same in the API so they should not be the same in Nextcord

### What is the feature request for?

The core library

### The Problem

Some details copied from this Discord thread: https://discord.com/channels/881118111967883295/1059571950432821408

discord.py issues a manual thread_join event depending on whether Discord says the thread was "newly created" or not, and whether the original thread could be seen in the raw data or not.
https://github.com/Rapptz/discord.py/blob/799e3c5bf09cedcd9b7e2b83df733910fa11532a/discord/state.py#L885
see lines 885 and 907

nextcord issues a on_thread_join event when it does not have the thread's object cached already.
https://github.com/nextcord/nextcord/blob/22eb5d169f6a05f2c813d72a158972a0ba3d7dc1/nextcord/state.py#L1507
line 1517 

`newly_created` is [a documented feature of the Discord API](https://discord.com/developers/docs/topics/gateway-events#thread-create) but nextcord disregards this useful information and users/clients cannot be aware of it unless doing some pretty heavy subclassing and patching, or trying to guess based on whether it has posts/members by the time that the bot manages to query the thread.

(computationally there is no guarantee that a new thread will be empty or near-empty by the time the result of the check comes back from the Discord API)

### The Ideal Solution

Personally when designing a middleware API for Python to work with an external API like Discord's, it's probably not good to create custom events like Discord.py does. That's my personal view on API design and I'm unaware of what the Nextcord project's view is generally.

My ideal solution would be to add a `newly_created` attribute onto Thread objects which is then passed to the `on_thread_join` event or its `raw` equivalent, and issue the event regardless of whether a thread is cached or not.

### The Current Solution

```py
    async def is_new_thread(self, thread):
        if len(await thread.history(limit=5).flatten()) <= 1:
            return False

        if len(thread.members) != 1:
            return False

        return True
```
or something like that

**Comment by ooliver1** [comment] 2023-01-07 19:08
Duplicate of #962 - the most recent issue created.

**Closed by ooliver1** 2023-01-07 19:08 UTC
