### ISSUE TITLE
Status not displaying properly

### ISSUE THREAD

**Issue by mab-mab** [nextcord/nextcord#605] opened 2022-04-17 12:48 UTC
### Summary

nextcord not responding with the correct Status

### Reproduction Steps

1. Enable presence/member intent
2. make a slash cmd that replies with `interaction.user.raw_status`

### Minimal Reproducible Code

```python
@client.slash_command(guild_ids=TESTING_GUILD_IDS)
async def presence(interaction: Interaction):
    await interaction.send(interaction.user.raw_status)
```

### Expected Results

show the correct status like dnd, online etc.

### Actual Results

It always displays offline whereas the user has a different status.
doing this `interaction.guild.get_member(interaction.user.id).raw_status` displays the right status but `interaction.user.raw_status` doesn't

### Intents

all

### System Information

- Python v3.9.1-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a9
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by koala9712** [comment] 2022-04-18 13:45
I can reproduce this on:
- python 3.9.10 as well as python3.9.12
- nextcord v2.0.0a10 as well as master branch (installed from git+https://gitub.com/nextcord/nextcord.git)
- windows 11 and ubuntu 18.04

and all their possible combinations

**Comment by koala9712** [comment] 2022-04-18 13:47
Looks like time to finish [this](https://github.com/nextcord/nextcord/blob/master/nextcord/interactions.py#L205) TODO
>         # TODO: there's a potential data loss here

**Comment by ooliver1** [comment] 2022-04-19 16:22
my assumption is discord does not send presence with the resolved member object, this *could* be resolved by using get_member if available which refers to the code linked by koala

**Comment by mab-mab** [comment] 2022-04-19 20:08
> my assumption is discord does not send presence with the resolved member object, this _could_ be resolved by using get_member if available which refers to the code linked by koala

I mean its not a big deal for me to write `interaction.guild.get_member(interaction.user.id).raw_status`. Just wanted to let you guys know.

**Closed** 2022-07-16 14:33 UTC
Labels: t: bug, p: low, s: awaiting review, 2.1
