### ISSUE TITLE
A built-in help command that includes pagination by default

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#121] opened 2021-09-02 17:52 UTC
### Summary

A built-in help command that includes pagination by default

### What is the feature request for?

The core library

### The Problem

The problem is we have to create our own pagination for commands by overriding some methods.

### The Ideal Solution

The ideal solution is to implement paginated help command that focuses on customisability (maybe).

### Additional Context

Ported over from [2.0 discord.py project](https://github.com/Rapptz/discord.py/projects/3#card-62697760)

**Comment by ooliver1** [comment] 2022-04-08 16:27
dupe of #120 ?

**Closed by ooliver1** 2022-04-08 16:27 UTC
Labels: t: enhancement, p: low, s: awaiting review
