### ISSUE TITLE
Components get moved randomly in a full Action Row on message/view update

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#18] opened 2021-08-28 15:44 UTC
### Link

https://github.com/Rapptz/discord.py/issues/7231

**Comment by ooliver1** [comment] 2022-06-11 12:07
superseeded by #331

test for github feature: duplicate of #331

**Comment by ooliver1** [comment] 2022-06-11 12:08
Duplicate of #331

**Comment by ooliver1** [comment] 2022-06-11 12:08
(superseeded but wanted to mark it as that)

**Closed** 2022-06-11 12:08 UTC
Labels: t: bug, ported, p: low, s: help appreciated
